import type { Locale } from "./config"

export const editorialPageDictionaries: Record<Locale, {
  events: {
    title: string; celebrations: string; celebrationParagraphs: string[]; floralEyebrow: string; floralTitle: string; floralText: string; corporateEyebrow: string; corporateTitle: string; corporateParagraphs: string[]; contact: string; findUs: string; formTitle: string; eventType: string; eventPlaceholder: string; submit: string; highlights: string[]
  }
  wedding: {
    title: string; eyebrow: string; intro: string; offerTitle: string; offerings: { title: string; description: string }[]; processTitle: string; processSteps: { title: string; text: string }[]; formEyebrow: string; formTitle: string; formText: string; subject: string; submit: string
  }
  rosedal: {
    title: string; eyebrow: string; intro: string[]; collection: string[]; stat: string; nurseryTitle: string; nursery: string[]; teaTitle: string; teaText: string; stories: string; rosesTitle: string; rosesEyebrow: string; roseDescriptions: string[]; available: string; ctaTitle: string; contact: string
  }
}> = {
  es: {
    events: {
      title: "Eventos en El Cangüé", celebrations: "Celebraciones", celebrationParagraphs: ["Bodas, cumpleaños, aniversarios y encuentros: en El Cangüé cada celebración se diseña a medida, desde reuniones íntimas hasta eventos de 400 personas.", "Coordinamos visitas a la estancia para conocer la propuesta y definir cada servicio. Nuestro equipo y una red de proveedores confiables pueden acompañar toda la planificación.", "Nuestra especialidad son las bodas. El Rosedal y la estructura transparente inmersa en el jardín crean un entorno único bajo el cielo del campo."], floralEyebrow: "Decoración floral", floralTitle: "Decoración de eventos", floralText: "Cultivamos nuestras propias flores y diseñamos cada ambientación para que ninguna celebración se parezca a otra.", corporateEyebrow: "Para empresas", corporateTitle: "Eventos empresariales", corporateParagraphs: ["El entorno natural, tranquilo y sin ruidos favorece el foco, la creatividad y el bienestar de los equipos.", "Adaptamos equipamiento, gastronomía, alojamiento, entretenimiento y espacios de trabajo a cada organización."], contact: "Contactar", findUs: "Encontranos", formTitle: "Organizá tu evento en la estancia", eventType: "Tipo de evento", eventPlaceholder: "Boda, cumpleaños, evento empresarial…", submit: "Consultar por mi evento", highlights: ["Hasta 400 invitados", "Propuesta personalizada", "Alojamiento boutique", "Proveedores coordinados"],
    },
    wedding: {
      title: "Destination Wedding", eyebrow: "Una boda boutique en el corazón del campo uruguayo", intro: "Celebrá una boda destino en una auténtica estancia uruguaya, rodeada de naturaleza y con cada detalle pensado para crear un recuerdo inolvidable.", offerTitle: "Qué ofrecemos", offerings: [
        { title: "Un entorno natural incomparable", description: "Paisajes abiertos, jardines históricos y la tranquilidad del campo para una celebración con identidad propia." },
        { title: "Temporada ideal para bodas", description: "Primavera y otoño ofrecen temperaturas agradables y una luz excepcional para celebrar al aire libre." },
        { title: "Ceremonias al atardecer", description: "El horizonte uruguayo crea un escenario cálido y único para la ceremonia y las fotografías." },
        { title: "Suite nupcial y alojamiento boutique", description: "Habitaciones con personalidad para los novios y opciones de hospedaje para sus invitados." },
        { title: "Gastronomía local", description: "Menús personalizados con productos de la región y alternativas para diferentes preferencias." },
        { title: "Organización integral", description: "Acompañamos la planificación y coordinamos proveedores para que puedan disfrutar cada momento." },
      ], processTitle: "Un proceso acompañado", processSteps: [{ title: "Primera conversación", text: "Conocemos su historia, fechas tentativas y prioridades." }, { title: "Propuesta a medida", text: "Diseñamos espacios, servicios y una hoja de ruta clara." }, { title: "Celebrar sin apuro", text: "Coordinamos cada detalle para que vivan plenamente el encuentro." }], formEyebrow: "Empecemos a imaginarla", formTitle: "Tu boda en El Cangüé", formText: "Contanos la fecha estimada, cantidad de invitados y el estilo de celebración que imaginan.", subject: "Consulta Destination Wedding", submit: "Consultar por nuestra boda",
    },
    rosedal: {
      title: "Nuestro Rosedal", eyebrow: "El alma viva de El Cangüé", intro: ["El jardín de la estancia está en evolución constante: cambia con las estaciones y siempre ofrece un rincón nuevo por descubrir.", "El Rosedal de la Abuela Anita es el corazón del parque y uno de nuestros espacios preferidos para bodas, visitas y encuentros alrededor del té.", "La pasión por las rosas nació con nuestra abuela Anita. A partir de sus plantas comenzamos una tarea de rescate, estudio y conservación de variedades antiguas."], collection: ["Rosas de té", "Noisette", "Polyantha", "Portland", "Híbridos antiguos y especies botánicas", "Híbridos perpetuos"], stat: "Más de 500 ejemplares con historias desde 1450", nurseryTitle: "Nuestro vivero", nursery: ["En la estancia funciona un vivero dedicado a reproducir rosales y plantas acompañantes. Su trabajo sostiene y amplía la colección.", "Recibimos con agenda previa a aficionados, clubes de jardinería y grupos interesados en visitas guiadas e intercambios."], teaTitle: "Blend de té “Abuela Anita”", teaText: "Una mezcla aromática inspirada en el jardín, desarrollada con pétalos de rosa y seleccionada para acompañar nuestra pastelería casera.", stories: "Donde nacen nuevas historias", rosesTitle: "Nuestras rosas", rosesEyebrow: "Variedades creadas en El Cangüé", roseDescriptions: ["Rosal trepador de flor grande, perfume abundante y carácter romántico.", "Una variedad de perfume clásico, floración generosa y presencia delicada.", "Híbrido criollo de gran porte, seleccionado por su vigor y la forma de sus flores.", "Variedad vigorosa de rosas grandes, color profundo y fragancia suave pero persistente."], available: "Variedades disponibles por temporada", ctaTitle: "¿Querés llevar una parte de El Cangüé a tu jardín?", contact: "Contactar",
    },
  },
  en: {
    events: { title: "Events at El Cangüé", celebrations: "Celebrations", celebrationParagraphs: ["Weddings, birthdays, anniversaries and gatherings: every celebration is tailored, from intimate meetings to events for 400 guests.", "Visit the estancia to explore the possibilities and define every service with our team and trusted suppliers.", "Weddings are our speciality. The rose garden and transparent pavilion create a unique setting beneath the country sky."], floralEyebrow: "Floral design", floralTitle: "Event styling", floralText: "We grow our own flowers and create a distinct atmosphere for every celebration.", corporateEyebrow: "For companies", corporateTitle: "Corporate events", corporateParagraphs: ["The peaceful natural surroundings support focus, creativity and team wellbeing.", "We tailor equipment, food, accommodation, entertainment and workspaces to each organisation."], contact: "Contact us", findUs: "Find us", formTitle: "Plan your event at the estancia", eventType: "Event type", eventPlaceholder: "Wedding, birthday, corporate event…", submit: "Enquire about my event", highlights: ["Up to 400 guests", "Tailored proposal", "Boutique lodging", "Coordinated suppliers"] },
    wedding: { title: "Destination Wedding", eyebrow: "A boutique wedding in the heart of rural Uruguay", intro: "Celebrate your destination wedding at an authentic Uruguayan estancia, surrounded by nature and thoughtful details.", offerTitle: "What we offer", offerings: [{ title: "An exceptional natural setting", description: "Open landscapes, historic gardens and country calm give your celebration a unique identity." }, { title: "Ideal wedding seasons", description: "Spring and autumn bring comfortable weather and beautiful outdoor light." }, { title: "Sunset ceremonies", description: "The Uruguayan horizon creates a warm backdrop for ceremonies and photographs." }, { title: "Bridal suite and boutique lodging", description: "Characterful rooms for the couple and accommodation options for guests." }, { title: "Local cuisine", description: "Tailored menus using regional produce and options for different preferences." }, { title: "Complete planning", description: "We coordinate the plan and suppliers so you can enjoy every moment." }], processTitle: "Supported at every step", processSteps: [{ title: "First conversation", text: "We learn your story, possible dates and priorities." }, { title: "A tailored proposal", text: "We design the spaces, services and a clear roadmap." }, { title: "Celebrate with ease", text: "We coordinate every detail so you can enjoy the gathering." }], formEyebrow: "Let’s imagine it together", formTitle: "Your wedding at El Cangüé", formText: "Tell us your estimated date, guest count and the celebration style you envision.", subject: "Destination Wedding enquiry", submit: "Enquire about our wedding" },
    rosedal: { title: "Our Rose Garden", eyebrow: "The living soul of El Cangüé", intro: ["The estancia garden is always evolving with the seasons and revealing new corners.", "Grandmother Anita’s Rose Garden is the heart of the park and a favourite setting for weddings, visits and tea.", "Our passion began with Anita’s plants and grew into a programme to rescue, study and preserve old varieties."], collection: ["Tea roses", "Noisette", "Polyantha", "Portland", "Old hybrids and botanical species", "Hybrid perpetuals"], stat: "More than 500 specimens with stories dating back to 1450", nurseryTitle: "Our nursery", nursery: ["Our nursery propagates roses and companion plants, maintaining and expanding the collection.", "Pre-booked guided visits welcome enthusiasts, gardening clubs and specialist groups."], teaTitle: "‘Grandmother Anita’ tea blend", teaText: "An aromatic blend inspired by the garden, made with rose petals and served with our home baking.", stories: "Where new stories begin", rosesTitle: "Our roses", rosesEyebrow: "Varieties created at El Cangüé", roseDescriptions: ["A climbing rose with large flowers, abundant fragrance and romantic character.", "A generous flowering variety with a classic scent and delicate presence.", "A vigorous local hybrid selected for its stature and flower shape.", "A strong variety with large, deep-coloured roses and a lasting fragrance."], available: "Varieties available seasonally", ctaTitle: "Would you like to take a piece of El Cangüé into your garden?", contact: "Contact us" },
  },
  fr: {
    events: { title: "Événements à El Cangüé", celebrations: "Célébrations", celebrationParagraphs: ["Mariages, anniversaires et rencontres : chaque célébration est conçue sur mesure, des réunions intimes aux événements de 400 personnes.", "Visitez l’estancia pour découvrir les possibilités et définir chaque service avec notre équipe.", "Les mariages sont notre spécialité. La roseraie et la structure transparente offrent un cadre unique sous le ciel de la campagne."], floralEyebrow: "Décoration florale", floralTitle: "Décoration d’événements", floralText: "Nous cultivons nos fleurs et créons une atmosphère unique pour chaque célébration.", corporateEyebrow: "Pour les entreprises", corporateTitle: "Événements professionnels", corporateParagraphs: ["Le cadre naturel favorise concentration, créativité et bien-être des équipes.", "Nous adaptons équipements, gastronomie, hébergement et espaces de travail à chaque organisation."], contact: "Nous contacter", findUs: "Nous trouver", formTitle: "Organisez votre événement à l’estancia", eventType: "Type d’événement", eventPlaceholder: "Mariage, anniversaire, événement d’entreprise…", submit: "Demander des informations", highlights: ["Jusqu’à 400 invités", "Proposition sur mesure", "Hébergement boutique", "Prestataires coordonnés"] },
    wedding: { title: "Mariage destination", eyebrow: "Un mariage boutique au cœur de la campagne uruguayenne", intro: "Célébrez votre mariage dans une authentique estancia uruguayenne, entourée de nature et de détails soignés.", offerTitle: "Ce que nous proposons", offerings: [{ title: "Un cadre naturel incomparable", description: "Paysages ouverts, jardins historiques et calme de la campagne." }, { title: "Saisons idéales", description: "Le printemps et l’automne offrent un climat agréable et une lumière exceptionnelle." }, { title: "Cérémonies au coucher du soleil", description: "L’horizon uruguayen crée un décor chaleureux." }, { title: "Suite nuptiale et hébergement", description: "Des chambres de caractère pour le couple et les invités." }, { title: "Gastronomie locale", description: "Des menus personnalisés à base de produits régionaux." }, { title: "Organisation complète", description: "Nous coordonnons la préparation et les prestataires." }], processTitle: "Un accompagnement à chaque étape", processSteps: [{ title: "Premier échange", text: "Nous découvrons votre histoire, vos dates et priorités." }, { title: "Proposition sur mesure", text: "Nous concevons les espaces, services et le calendrier." }, { title: "Célébrer sereinement", text: "Nous coordonnons chaque détail pour profiter pleinement." }], formEyebrow: "Imaginons-la ensemble", formTitle: "Votre mariage à El Cangüé", formText: "Indiquez-nous la date envisagée, le nombre d’invités et le style souhaité.", subject: "Demande Mariage destination", submit: "Parler de notre mariage" },
    rosedal: { title: "Notre Roseraie", eyebrow: "L’âme vivante d’El Cangüé", intro: ["Le jardin évolue avec les saisons et révèle toujours de nouveaux recoins.", "La Roseraie de Grand-mère Anita est le cœur du parc, idéale pour mariages, visites et thé.", "Notre passion est née des plantes d’Anita et d’un travail de sauvegarde des variétés anciennes."], collection: ["Rosiers thé", "Noisette", "Polyantha", "Portland", "Hybrides anciens et espèces botaniques", "Hybrides remontants"], stat: "Plus de 500 spécimens dont l’histoire remonte à 1450", nurseryTitle: "Notre pépinière", nursery: ["La pépinière reproduit rosiers et plantes compagnes pour enrichir la collection.", "Des visites guidées sur réservation accueillent amateurs et clubs de jardinage."], teaTitle: "Thé « Grand-mère Anita »", teaText: "Un mélange aromatique inspiré du jardin, aux pétales de rose, servi avec nos pâtisseries maison.", stories: "Là où naissent de nouvelles histoires", rosesTitle: "Nos roses", rosesEyebrow: "Variétés créées à El Cangüé", roseDescriptions: ["Rosier grimpant à grandes fleurs et parfum généreux.", "Variété délicate au parfum classique et à la floraison abondante.", "Hybride local vigoureux sélectionné pour son port.", "Variété robuste aux grandes roses et au parfum persistant."], available: "Variétés disponibles selon la saison", ctaTitle: "Envie d’emporter un peu d’El Cangüé dans votre jardin ?", contact: "Nous contacter" },
  },
  pt: {
    events: { title: "Eventos no El Cangüé", celebrations: "Celebrações", celebrationParagraphs: ["Casamentos, aniversários e encontros: cada celebração é personalizada, de reuniões íntimas a eventos para 400 pessoas.", "Visite a estancia para conhecer as possibilidades e definir cada serviço com nossa equipe.", "Casamentos são nossa especialidade. O roseiral e a estrutura transparente criam um cenário único sob o céu do campo."], floralEyebrow: "Decoração floral", floralTitle: "Decoração de eventos", floralText: "Cultivamos nossas flores e criamos uma ambientação exclusiva para cada celebração.", corporateEyebrow: "Para empresas", corporateTitle: "Eventos empresariais", corporateParagraphs: ["O ambiente natural favorece foco, criatividade e bem-estar das equipes.", "Adaptamos equipamentos, gastronomia, hospedagem e espaços de trabalho a cada organização."], contact: "Entrar em contato", findUs: "Como chegar", formTitle: "Organize seu evento na estancia", eventType: "Tipo de evento", eventPlaceholder: "Casamento, aniversário, evento empresarial…", submit: "Consultar sobre meu evento", highlights: ["Até 400 convidados", "Proposta personalizada", "Hospedagem boutique", "Fornecedores coordenados"] },
    wedding: { title: "Destination Wedding", eyebrow: "Um casamento boutique no coração do campo uruguaio", intro: "Celebre seu casamento em uma autêntica estancia uruguaia, cercada de natureza e detalhes especiais.", offerTitle: "O que oferecemos", offerings: [{ title: "Um ambiente natural incomparável", description: "Paisagens abertas, jardins históricos e tranquilidade rural." }, { title: "Estações ideais", description: "Primavera e outono oferecem clima agradável e luz excepcional." }, { title: "Cerimônias ao pôr do sol", description: "O horizonte uruguaio cria um cenário acolhedor." }, { title: "Suíte nupcial e hospedagem", description: "Quartos cheios de personalidade para o casal e convidados." }, { title: "Gastronomia local", description: "Menus personalizados com produtos regionais." }, { title: "Organização completa", description: "Coordenamos o planejamento e os fornecedores." }], processTitle: "Acompanhamento em cada etapa", processSteps: [{ title: "Primeira conversa", text: "Conhecemos sua história, datas e prioridades." }, { title: "Proposta personalizada", text: "Desenhamos espaços, serviços e um roteiro claro." }, { title: "Celebrar com tranquilidade", text: "Coordenamos cada detalhe para vocês aproveitarem." }], formEyebrow: "Vamos imaginar juntos", formTitle: "Seu casamento no El Cangüé", formText: "Conte a data estimada, número de convidados e o estilo de celebração.", subject: "Consulta Destination Wedding", submit: "Consultar sobre nosso casamento" },
    rosedal: { title: "Nosso Roseiral", eyebrow: "A alma viva do El Cangüé", intro: ["O jardim evolui com as estações e sempre revela novos cantos.", "O Roseiral da Vovó Anita é o coração do parque, perfeito para casamentos, visitas e chá.", "Nossa paixão nasceu das plantas de Anita e do trabalho de preservação de variedades antigas."], collection: ["Rosas chá", "Noisette", "Polyantha", "Portland", "Híbridos antigos e espécies botânicas", "Híbridos perpétuos"], stat: "Mais de 500 exemplares com histórias desde 1450", nurseryTitle: "Nosso viveiro", nursery: ["O viveiro reproduz roseiras e plantas companheiras para manter e ampliar a coleção.", "Visitas guiadas com agendamento recebem aficionados e clubes de jardinagem."], teaTitle: "Blend de chá ‘Vovó Anita’", teaText: "Uma mistura aromática inspirada no jardim, com pétalas de rosa e nossa confeitaria caseira.", stories: "Onde nascem novas histórias", rosesTitle: "Nossas rosas", rosesEyebrow: "Variedades criadas no El Cangüé", roseDescriptions: ["Roseira trepadeira de flores grandes e perfume abundante.", "Variedade delicada, perfumada e de floração generosa.", "Híbrido local vigoroso selecionado pelo porte.", "Variedade forte de rosas grandes e fragrância persistente."], available: "Variedades disponíveis por temporada", ctaTitle: "Quer levar um pouco do El Cangüé para o seu jardim?", contact: "Entrar em contato" },
  },
}
